insert into dbo.menu (id, name, parentId, seq, descn) values ('1','Admin',null,1,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('2','User','1',1,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('3','Privilege','1',2,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('4','Menu','1',3,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('5','Add New User','2',1,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('6','Search User','2',2,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('7','View User Detail','2',3,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('8','Remove User','2',4,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('9','Add New Menu','4',1,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('10','List All Menus','4',2,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('11','Change Menu','4',3,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('12','Remove Menu','4',4,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('101','Login',null,101,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('102','Logout',null,102,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('103','Sitemap',null,103,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('104','FAQ',null,104,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('105','Q&A',null,105,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('201','Common',null,201,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('202','Code','201',1,'');
insert into dbo.menu (id, name, parentId, seq, descn) values ('203','Organization','201',2,'');
