CREATE TABLE STOCK_CODE(
	VER INTEGER NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	SHORT_CODE VARCHAR(10),
	ISSUE VARCHAR(200) NOT NULL,
	ISSUE_ENG VARCHAR(200),
	MARKET_TYPE VARCHAR(30),
	CONSTRAINT PK_STOCKCODE PRIMARY KEY(VER,CODE)
);